import { isApiError } from "@/lib/api/errors";

import type {
  CustomDictionary,
  DictionaryEntry,
  DictionaryEntryScalar,
  DictionaryField,
  DictionaryStatusFilter,
  SaveDictionaryFieldInput,
  WritableAttributeDataType,
} from "./types";
import { isAutoGeneratedDictionaryField } from "./dictionary-field-presets";

export interface DictionaryFieldDraftRow extends SaveDictionaryFieldInput {
  rowId: string;
}

const dictionaryExternalIdMaxLength = 80;

export function getDictionaryFilterCount(
  dictionaries: readonly CustomDictionary[],
  status: DictionaryStatusFilter,
): number {
  if (status === "all") {
    return dictionaries.length;
  }

  return dictionaries.filter((dictionary) => dictionary.status === status)
    .length;
}

export function filterDictionariesByStatus(
  dictionaries: readonly CustomDictionary[],
  status: DictionaryStatusFilter,
): CustomDictionary[] {
  if (status === "all") {
    return [...dictionaries];
  }

  return dictionaries.filter((dictionary) => dictionary.status === status);
}

export function buildDictionaryFieldDraftRows(
  fields: readonly DictionaryField[],
): DictionaryFieldDraftRow[] {
  return fields
    .map((field) => ({
      constraints: field.constraints,
      dataType: field.dataType,
      externalId: field.externalId,
      format: field.format,
      isUnique: field.isUnique,
      label: field.label,
      normalization: field.normalization,
      required: field.required,
      rowId: field.id,
      sortOrder: field.sortOrder,
      status: field.status,
    }))
    .sort((first, second) => first.sortOrder - second.sortOrder);
}

export function deriveDictionaryEntryLabel({
  fallback,
  fields,
  values,
}: {
  fallback?: string;
  fields: readonly DictionaryField[];
  values: Record<string, DictionaryEntryScalar | string | undefined>;
}): string {
  const orderedFields = fields
    .filter((field) => field.status === "active")
    .slice()
    .sort((first, second) => {
      const priorityDelta =
        getDisplayLabelPriority(first) - getDisplayLabelPriority(second);
      return priorityDelta || first.sortOrder - second.sortOrder;
    });

  for (const field of orderedFields) {
    const value = formatDictionaryEntryValue(values[field.externalId]).trim();

    if (value) {
      return value;
    }
  }

  return fallback?.trim() ?? "";
}

export function getDictionaryEntryDisplayField(
  fields: readonly DictionaryField[],
): DictionaryField | undefined {
  return fields
    .filter((field) => field.status === "active")
    .slice()
    .sort((first, second) => {
      const priorityDelta =
        getDisplayLabelPriority(first) - getDisplayLabelPriority(second);
      return priorityDelta || first.sortOrder - second.sortOrder;
    })[0];
}

export function toGeneratedExternalId(
  value: string,
  fallbackPrefix: string,
): string {
  const normalized = value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/gu, "_")
    .replace(/^_+|_+$/gu, "")
    .slice(0, dictionaryExternalIdMaxLength);

  if (normalized) {
    return normalized;
  }

  const fallback = `${fallbackPrefix}_${crypto.randomUUID().slice(0, 8)}`;
  return fallback.slice(0, dictionaryExternalIdMaxLength);
}

export function toSaveDictionaryFieldInput(
  rows: readonly DictionaryFieldDraftRow[],
): SaveDictionaryFieldInput[] {
  return rows
    .map((row, index) => ({
      constraints: row.constraints,
      dataType: row.dataType,
      externalId: row.externalId.trim(),
      format: row.format,
      isUnique: row.isUnique,
      label: row.label.trim(),
      normalization: row.normalization,
      required: row.required,
      sortOrder: row.sortOrder >= 0 ? row.sortOrder : index,
      status: row.status,
    }))
    .filter((row) => row.externalId || row.label);
}

export function getDuplicateDictionaryFieldIds(
  rows: readonly DictionaryFieldDraftRow[],
): string[] {
  const seen = new Set<string>();
  const duplicates = new Set<string>();

  for (const row of rows) {
    const normalized = row.externalId.trim();

    if (!normalized) {
      continue;
    }

    if (seen.has(normalized)) {
      duplicates.add(normalized);
    }

    seen.add(normalized);
  }

  return [...duplicates].sort();
}

export function parseJsonObject(input: string): Record<string, unknown> {
  const normalized = input.trim();

  if (!normalized) {
    return {};
  }

  const parsed: unknown = JSON.parse(normalized);

  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("JSON value must be an object.");
  }

  return parsed as Record<string, unknown>;
}

export function formatJsonObject(value: Record<string, unknown>): string {
  return Object.keys(value).length > 0 ? JSON.stringify(value, null, 2) : "";
}

export function formatDictionaryEntryValue(
  value: DictionaryEntryScalar | undefined,
): string {
  if (value === undefined || value === null) {
    return "";
  }

  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }

  return String(value);
}

export function formatDictionaryEntryInputValue(
  value: DictionaryEntryScalar | undefined,
  dataType: WritableAttributeDataType,
): string {
  const formatted = formatDictionaryEntryValue(value);

  if (dataType === "datetime") {
    return toDateTimeLocalInputValue(formatted);
  }

  return formatted;
}

export function parseDictionaryEntryValue(
  value: string,
  dataType: WritableAttributeDataType,
): DictionaryEntryScalar {
  const normalized = value.trim();

  if (!normalized) {
    return null;
  }

  if (dataType === "integer") {
    const parsed = Number(normalized);
    return Number.isInteger(parsed) ? parsed : normalized;
  }

  if (dataType === "number") {
    const parsed = Number(normalized);
    return Number.isFinite(parsed) ? parsed : normalized;
  }

  if (dataType === "boolean") {
    if (normalized.toLowerCase() === "true") {
      return true;
    }
    if (normalized.toLowerCase() === "false") {
      return false;
    }
  }

  if (dataType === "datetime") {
    return toApiDateTimeValue(normalized);
  }

  return normalized;
}

export function isDictionaryEntryValueMissing(value: string): boolean {
  return !value.trim();
}

export function getDictionaryEntryDisplayFields(
  entry: DictionaryEntry,
  fields: readonly DictionaryField[],
): string[] {
  return fields
    .filter((field) => field.status === "active")
    .slice()
    .sort((first, second) => first.sortOrder - second.sortOrder)
    .slice(0, 3)
    .map((field) => {
      const value = formatDictionaryEntryValue(entry.values[field.externalId]);
      return value ? `${field.label}: ${value}` : "";
    })
    .filter(Boolean);
}

export function getDictionaryValidationMessages(error: unknown): string[] {
  if (!isApiError(error)) {
    return [];
  }

  const messages: string[] = [];
  addDetailMessage(messages, error.details.unknown_fields, "Unknown fields");
  addDetailMessage(
    messages,
    error.details.missing_required_fields,
    "Missing required fields",
  );
  addDetailMessage(
    messages,
    error.details.invalid_type_fields,
    "Invalid type fields",
  );
  addDetailMessage(
    messages,
    error.details.duplicate_unique_fields,
    "Duplicate unique fields",
  );
  addDetailMessage(
    messages,
    error.details.constraint_failed_fields,
    "Constraint failures",
  );
  return messages;
}

function addDetailMessage(
  messages: string[],
  value: unknown,
  label: string,
): void {
  const items = stringList(value);

  if (items.length > 0) {
    messages.push(`${label}: ${items.join(", ")}`);
  }
}

function stringList(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value.filter((item): item is string => typeof item === "string");
}

function getDisplayLabelPriority(field: DictionaryField): number {
  if (isAutoGeneratedDictionaryField(field)) {
    return 4;
  }

  const normalized = `${field.externalId} ${field.label}`
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/gu, "")
    .toLowerCase();

  if (/\b(name|label|nazwa|etykieta)\b/u.test(normalized)) {
    return 0;
  }

  if (field.dataType === "string") {
    return 1;
  }

  if (field.dataType === "integer" || field.dataType === "number") {
    return 2;
  }

  return 3;
}

function toDateTimeLocalInputValue(value: string): string {
  const normalized = value.trim();
  const match = normalized.match(
    /^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2})(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:\d{2})?$/u,
  );
  return match?.[1] ?? normalized;
}

function toApiDateTimeValue(value: string): string {
  const match = value.match(/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2})$/u);
  if (!match) {
    return value;
  }
  return `${match[1]}:00`;
}

export * from "./dictionary-field-presets";
