import type { DictionaryField, WritableAttributeDataType } from "./types";

export const dictionaryFieldTypeOptions = [
  "string",
  "uuid",
  "uuid_auto",
  "integer_identifier",
  "integer_identifier_auto",
  "integer",
  "number",
  "boolean",
  "date",
  "datetime",
] as const;

export type DictionaryFieldTypeOption =
  (typeof dictionaryFieldTypeOptions)[number];

const dictionaryFieldTypeFormatKeys = ["generation", "semantic_type"] as const;
const dictionaryFieldGenerationAuto = "auto";
const dictionaryFieldGenerationManual = "manual";
const dictionaryFieldSemanticNumericIdentifier = "numeric_identifier";
const dictionaryFieldSemanticUuid = "uuid";
const uuidConstraintPattern =
  "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$";

export function getDictionaryFieldTypeOption(
  dataType: WritableAttributeDataType,
  format: Record<string, unknown>,
): DictionaryFieldTypeOption {
  const semanticType = stringRecordValue(format, "semantic_type");
  const generation =
    stringRecordValue(format, "generation") === dictionaryFieldGenerationAuto
      ? dictionaryFieldGenerationAuto
      : dictionaryFieldGenerationManual;

  if (dataType === "string" && semanticType === dictionaryFieldSemanticUuid) {
    return generation === dictionaryFieldGenerationAuto ? "uuid_auto" : "uuid";
  }

  if (
    dataType === "integer" &&
    semanticType === dictionaryFieldSemanticNumericIdentifier
  ) {
    return generation === dictionaryFieldGenerationAuto
      ? "integer_identifier_auto"
      : "integer_identifier";
  }

  return dataType;
}

export function applyDictionaryFieldTypeOption(
  option: DictionaryFieldTypeOption,
  current: {
    constraints: Record<string, number | string>;
    format: Record<string, unknown>;
  },
): {
  constraints: Record<string, number | string>;
  dataType: WritableAttributeDataType;
  format: Record<string, unknown>;
} {
  const constraints = withoutIdentifierPresetConstraints(current.constraints);
  const format = withoutDictionaryFieldTypeFormat(current.format);

  if (option === "uuid" || option === "uuid_auto") {
    return {
      constraints: {
        ...constraints,
        max_length: 36,
        pattern: uuidConstraintPattern,
      },
      dataType: "string",
      format: {
        ...format,
        generation:
          option === "uuid_auto"
            ? dictionaryFieldGenerationAuto
            : dictionaryFieldGenerationManual,
        semantic_type: dictionaryFieldSemanticUuid,
      },
    };
  }

  if (option === "integer_identifier" || option === "integer_identifier_auto") {
    return {
      constraints: {
        ...constraints,
        min_value: option === "integer_identifier_auto" ? 1 : 0,
      },
      dataType: "integer",
      format: {
        ...format,
        generation:
          option === "integer_identifier_auto"
            ? dictionaryFieldGenerationAuto
            : dictionaryFieldGenerationManual,
        semantic_type: dictionaryFieldSemanticNumericIdentifier,
      },
    };
  }

  return {
    constraints,
    dataType: option,
    format,
  };
}

export function isAutoGeneratedDictionaryField(
  field: DictionaryField,
): boolean {
  const type = getDictionaryFieldTypeOption(field.dataType, field.format);
  return type === "uuid_auto" || type === "integer_identifier_auto";
}

export function generateDictionaryFieldValue(field: DictionaryField): string {
  const type = getDictionaryFieldTypeOption(field.dataType, field.format);

  if (type === "uuid_auto" || type === "integer_identifier_auto") {
    return "";
  }

  return "";
}

function withoutDictionaryFieldTypeFormat(
  format: Record<string, unknown>,
): Record<string, unknown> {
  const result = { ...format };

  for (const key of dictionaryFieldTypeFormatKeys) {
    delete result[key];
  }

  return result;
}

function withoutIdentifierPresetConstraints(
  constraints: Record<string, number | string>,
): Record<string, number | string> {
  const result = { ...constraints };

  if (result.pattern === uuidConstraintPattern) {
    delete result.pattern;
  }

  if (result.max_length === 36) {
    delete result.max_length;
  }

  if (result.min_value === 0 || result.min_value === 1) {
    delete result.min_value;
  }

  return result;
}

function stringRecordValue(
  value: Record<string, unknown>,
  key: string,
): string | null {
  const candidate = value[key];
  return typeof candidate === "string" ? candidate : null;
}
