"""Constants for OCR pipeline run domain models."""

OCR_PIPELINE_RUN_ERROR_CODE_MAX_LENGTH = 100
OCR_PIPELINE_RUN_ERROR_MESSAGE_MAX_LENGTH = 200
OCR_PIPELINE_RUN_STEP_ID_MAX_LENGTH = 80
OCR_PIPELINE_RUN_STEP_TYPE_MAX_LENGTH = 80
OCR_PIPELINE_RUN_IMPLEMENTATION_ID_MAX_LENGTH = 160
OCR_PIPELINE_RUN_DISPLAY_NAME_MAX_LENGTH = 200
OCR_PIPELINE_RUN_CATALOG_VALUE_MAX_LENGTH = 256
OCR_PIPELINE_RUN_ACTOR_ID_MAX_LENGTH = 128
OCR_PIPELINE_RUN_ACTOR_LOGIN_MAX_LENGTH = 320
OCR_PIPELINE_RUN_CONNECTOR_VALUE_MAX_LENGTH = 200
OCR_PIPELINE_RUN_DOCUMENT_REFERENCE_MAX_LENGTH = 256
OCR_PIPELINE_RUN_MAX_STEP_COUNT = 16
OCR_PIPELINE_RUN_LIST_DEFAULT_LIMIT = 20
OCR_PIPELINE_RUN_LIST_MAX_LIMIT = 100
