"""Attribute definition catalog constants."""

ATTRIBUTE_ALLOWED_VALUE_MAX_LENGTH = 200
ATTRIBUTE_CATEGORY_DEFAULT = "Bez kategorii"
ATTRIBUTE_CATEGORY_MAX_LENGTH = 120
ATTRIBUTE_COMMENT_MAX_LENGTH = 2000
ATTRIBUTE_CONSTRAINT_PATTERN_MAX_LENGTH = 500
ATTRIBUTE_ID_MAX_LENGTH = 80
ATTRIBUTE_LLM_CONTEXT_MAX_LENGTH = 1000
ATTRIBUTE_NAME_MAX_LENGTH = 200
