subscription_id = "ade38c32-9ade-4049-a9e1-bce6d1692438"
app_id          = "ocr"
environment     = "test"
instance_number = "01"

application_resource_group_name = "rg-ocr-test"

workload_identity_workloads = [
  "web",
  "api",
  "api-migrator",
  "dapr-servicebus-api",
  "dapr-servicebus-worker",
  "dapr-servicebus-llmmagic",
  "llmmagic",
  "worker",
]

role_assignments = {
  acr-pull-web          = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ContainerRegistry/registries/ee7c45crocrtest01", role_definition_name = "AcrPull", workload_identity_key = "web", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  acr-pull-api          = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ContainerRegistry/registries/ee7c45crocrtest01", role_definition_name = "AcrPull", workload_identity_key = "api", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  acr-pull-api-migrator = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ContainerRegistry/registries/ee7c45crocrtest01", role_definition_name = "AcrPull", workload_identity_key = "api-migrator", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  acr-pull-llmmagic     = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ContainerRegistry/registries/ee7c45crocrtest01", role_definition_name = "AcrPull", workload_identity_key = "llmmagic", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  acr-pull-worker       = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ContainerRegistry/registries/ee7c45crocrtest01", role_definition_name = "AcrPull", workload_identity_key = "worker", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }

  github-build-acr-push        = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ContainerRegistry/registries/ee7c45crocrtest01", role_definition_name = "AcrPush", principal_id = "cdd15ce2-f0e1-4bc8-a686-530a2ad6c582", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  github-build-acr-read        = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ContainerRegistry/registries/ee7c45crocrtest01", role_definition_name = "Reader", principal_id = "cdd15ce2-f0e1-4bc8-a686-530a2ad6c582", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  github-deploy-acr-pull       = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ContainerRegistry/registries/ee7c45crocrtest01", role_definition_name = "AcrPull", principal_id = "cdd15ce2-f0e1-4bc8-a686-530a2ad6c582", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  # github-deploy-acr-read       = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ContainerRegistry/registries/ee7c45crocrtest01", role_definition_name = "Reader", principal_id = "cdd15ce2-f0e1-4bc8-a686-530a2ad6c582", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  github-deploy-container-apps = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test", role_definition_name = "Container Apps Contributor", principal_id = "cdd15ce2-f0e1-4bc8-a686-530a2ad6c582", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }

  api-inbox              = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/inbox", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "api", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  llmmagic-inbox         = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/inbox", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "llmmagic", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  llmmagic-ocr-artifacts = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/ocr-artifacts", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "llmmagic", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  llmmagic-preprocessed  = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/preprocessed", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "llmmagic", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  llmmagic-previews      = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/previews", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "llmmagic", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  llmmagic-quarantine    = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/quarantine", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "llmmagic", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  worker-archive         = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/archive", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "worker", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  worker-inbox           = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/inbox", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "worker", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  worker-ocr-artifacts   = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/ocr-artifacts", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "worker", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  worker-preprocessed    = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/preprocessed", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "worker", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  worker-previews        = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/previews", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "worker", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  worker-quarantine      = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01/blobServices/default/containers/quarantine", role_definition_name = "Storage Blob Data Contributor", workload_identity_key = "worker", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }

  document-intelligence-storage-read      = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.Storage/storageAccounts/ee7c45stocrdoctest01", role_definition_name = "Storage Blob Data Reader", principal_id = "a59da086-b198-4319-bf24-0cac51224a8a", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  llmmagic-document-intelligence          = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.CognitiveServices/accounts/ee7c45diocrtest01", role_definition_name = "Cognitive Services User", workload_identity_key = "llmmagic", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  llmmagic-foundry-user                   = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.CognitiveServices/accounts/ais-ocr-test-01", role_definition_name = "Cognitive Services User", workload_identity_key = "llmmagic", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  llmmagic-foundry-openai                 = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.CognitiveServices/accounts/ais-ocr-test-01", role_definition_name = "Cognitive Services OpenAI User", workload_identity_key = "llmmagic", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  dapr-api-send-document-processing       = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ServiceBus/namespaces/ee7c45sbnsocrtest01/queues/document-processing", role_definition_name = "Azure Service Bus Data Sender", workload_identity_key = "dapr-servicebus-api", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  dapr-api-receive-processing-results     = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ServiceBus/namespaces/ee7c45sbnsocrtest01/queues/processing-results", role_definition_name = "Azure Service Bus Data Receiver", workload_identity_key = "dapr-servicebus-api", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  dapr-worker-receive-document-processing = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ServiceBus/namespaces/ee7c45sbnsocrtest01/queues/document-processing", role_definition_name = "Azure Service Bus Data Receiver", workload_identity_key = "dapr-servicebus-worker", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  dapr-worker-send-processing-results     = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ServiceBus/namespaces/ee7c45sbnsocrtest01/queues/processing-results", role_definition_name = "Azure Service Bus Data Sender", workload_identity_key = "dapr-servicebus-worker", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
  dapr-llmmagic-send-processing-results   = { scope = "/subscriptions/ade38c32-9ade-4049-a9e1-bce6d1692438/resourceGroups/rg-ocr-test/providers/Microsoft.ServiceBus/namespaces/ee7c45sbnsocrtest01/queues/processing-results", role_definition_name = "Azure Service Bus Data Sender", workload_identity_key = "dapr-servicebus-llmmagic", principal_type = "ServicePrincipal", skip_service_principal_aad_check = true }
}
