"use client";

import { useTranslations } from "next-intl";
import { useMemo, useState, type FormEvent } from "react";

import { CatalogFormSection } from "@/components/admin/catalog/catalog-form-section";
import {
  CatalogFormActions,
  CatalogFormSheet,
} from "@/components/admin/catalog/catalog-form-sheet";
import {
  CatalogNotice,
  FieldShell,
  getCatalogErrorMessage,
} from "@/components/admin/catalog/catalog-shared";
import { FieldGroup } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import type {
  DictionaryEntry,
  DictionaryField,
  UpsertDictionaryEntryInput,
} from "@/lib/admin-settings/types";
import {
  deriveDictionaryEntryLabel,
  formatDictionaryEntryInputValue,
  generateDictionaryFieldValue,
  getDictionaryEntryDisplayField,
  getDictionaryFieldTypeOption,
  getDictionaryValidationMessages,
  isAutoGeneratedDictionaryField,
  isDictionaryEntryValueMissing,
  parseDictionaryEntryValue,
  toGeneratedExternalId,
} from "@/lib/admin-settings/view-model";

type DictionaryEntryFormMode =
  | { kind: "create" }
  | { item: DictionaryEntry; kind: "edit" };

interface DictionaryEntryFormProps {
  error: unknown;
  fields: DictionaryField[];
  isPending: boolean;
  mode: DictionaryEntryFormMode;
  onCancel: () => void;
  onSubmit: (
    mode: DictionaryEntryFormMode,
    input: UpsertDictionaryEntryInput,
  ) => void;
}

interface DictionaryEntryFormErrors {
  externalId?: string;
}

export function DictionaryEntryForm({
  error,
  fields,
  isPending,
  mode,
  onCancel,
  onSubmit,
}: DictionaryEntryFormProps) {
  const t = useTranslations("AdminSettings.customDictionaries.entriesForm");
  const common = useTranslations("AdminSettings.common");
  const initial = useMemo(
    () => getInitialFormState(mode, fields),
    [fields, mode],
  );
  const [externalId, setExternalId] = useState(initial.externalId);
  const [values, setValues] = useState(initial.values);
  const [errors, setErrors] = useState<DictionaryEntryFormErrors>({});
  const [valueErrors, setValueErrors] = useState<Record<string, string>>({});
  const hasValueErrors = Object.values(valueErrors).some(Boolean);
  const saveErrorMessage = error
    ? getCatalogErrorMessage(error, t("errors.saveFailed"))
    : null;
  const visibleFooterError = hasValueErrors
    ? t("errors.fixFields")
    : saveErrorMessage;
  const activeFields = fields
    .filter((field) => field.status === "active")
    .slice()
    .sort((first, second) => first.sortOrder - second.sortOrder);

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const nextValueErrors: Record<string, string> = {};
    const normalizedLabel = deriveDictionaryEntryLabel({
      fallback: mode.kind === "edit" ? mode.item.label : undefined,
      fields: activeFields,
      values,
    });

    for (const field of activeFields) {
      if (
        field.required &&
        !isAutoGeneratedDictionaryField(field) &&
        isDictionaryEntryValueMissing(values[field.externalId] ?? "")
      ) {
        nextValueErrors[field.externalId] = t("errors.requiredValue", {
          field: field.label,
        });
      }
    }

    const manualDisplayFields = activeFields.filter(
      (field) => !isAutoGeneratedDictionaryField(field),
    );

    if (!normalizedLabel && manualDisplayFields.length > 0) {
      const displayField = getDictionaryEntryDisplayField(manualDisplayFields);

      if (displayField) {
        nextValueErrors[displayField.externalId] = t(
          "errors.displayValueRequired",
        );
      }
    }

    setValueErrors(nextValueErrors);
    setErrors({});

    if (Object.keys(nextValueErrors).length > 0) {
      return;
    }

    const normalizedExternalId =
      externalId.trim() ||
      toGeneratedExternalId(
        normalizedLabel || firstFilledValue(values) || "entry",
        "entry",
      );

    onSubmit(mode, {
      externalId: normalizedExternalId,
      label: normalizedLabel || normalizedExternalId,
      sortOrder: initial.sortOrder,
      values: Object.fromEntries(
        activeFields.map((field) => [
          field.externalId,
          parseDictionaryEntryValue(
            values[field.externalId] ?? "",
            field.dataType,
          ),
        ]),
      ),
    });
  }

  return (
    <CatalogFormSheet
      description={
        mode.kind === "create"
          ? t("createDescription")
          : t("editDescription", { id: mode.item.externalId })
      }
      footer={
        <CatalogFormActions
          cancelLabel={t("cancel")}
          error={visibleFooterError}
          isPending={isPending}
          onCancel={onCancel}
          saveDisabled={activeFields.length === 0}
          saveLabel={t("save")}
          savingLabel={t("saving")}
        />
      }
      onSubmit={handleSubmit}
      title={mode.kind === "create" ? t("createTitle") : t("editTitle")}
    >
      <FieldGroup>
        {activeFields.map((field) => (
          <FieldShell
            description={getFieldDescription(field, t)}
            error={valueErrors[field.externalId]}
            htmlFor={`entry-value-${field.externalId}`}
            key={field.id}
            label={field.label}
            required={field.required}
            requiredLabel={common("requiredField")}
          >
            {renderFieldInput(field)}
          </FieldShell>
        ))}

        {activeFields.length === 0 ? (
          <CatalogNotice
            description={t("noFieldsDescription")}
            title={t("noFieldsTitle")}
          />
        ) : null}

        <CatalogFormSection
          description={t("integration.description")}
          summary={
            <span className="font-mono">
              {externalId || t("integration.generated")}
            </span>
          }
          title={t("integration.title")}
        >
          <FieldShell
            description={t("integration.externalIdDescription")}
            error={errors.externalId}
            htmlFor="entry-external-id"
            label={t("fields.externalId")}
          >
            <Input
              aria-invalid={Boolean(errors.externalId)}
              disabled={isPending}
              id="entry-external-id"
              onChange={(event) => {
                setExternalId(event.target.value);
                setErrors((current) => ({
                  ...current,
                  externalId: undefined,
                }));
              }}
              placeholder={t("integration.externalIdPlaceholder")}
              value={externalId}
            />
          </FieldShell>
        </CatalogFormSection>
      </FieldGroup>

      {error ? (
        <CatalogNotice
          description={getDictionaryValidationMessages(error).join("\n")}
          title={getCatalogErrorMessage(error, t("errors.saveFailed"))}
          tone="danger"
        />
      ) : null}
    </CatalogFormSheet>
  );

  function renderFieldInput(field: DictionaryField) {
    const fieldValue = values[field.externalId] ?? "";
    const disabled = isPending || isAutoGeneratedDictionaryField(field);

    if (field.dataType === "boolean") {
      return (
        <ToggleGroup
          aria-label={field.label}
          onValueChange={(value) => setFieldValue(field.externalId, value)}
          type="single"
          value={fieldValue}
          variant="outline"
        >
          <ToggleGroupItem disabled={disabled} size="sm" value="true">
            {t("boolean.true")}
          </ToggleGroupItem>
          <ToggleGroupItem disabled={disabled} size="sm" value="false">
            {t("boolean.false")}
          </ToggleGroupItem>
        </ToggleGroup>
      );
    }

    return (
      <Input
        aria-invalid={Boolean(valueErrors[field.externalId])}
        disabled={disabled}
        id={`entry-value-${field.externalId}`}
        inputMode={getInputMode(field)}
        onChange={(event) =>
          setFieldValue(field.externalId, event.target.value)
        }
        type={getInputType(field)}
        value={fieldValue}
      />
    );
  }

  function setFieldValue(fieldExternalId: string, value: string) {
    setValues((current) => ({
      ...current,
      [fieldExternalId]: value,
    }));
    setValueErrors((current) => ({
      ...current,
      [fieldExternalId]: "",
    }));
  }
}

function getInitialFormState(
  mode: DictionaryEntryFormMode,
  fields: readonly DictionaryField[],
) {
  if (mode.kind === "create") {
    return {
      externalId: "",
      sortOrder: null,
      values: Object.fromEntries(
        fields.map((field) => [
          field.externalId,
          generateDictionaryFieldValue(field),
        ]),
      ) as Record<string, string>,
    };
  }

  return {
    externalId: mode.item.externalId,
    sortOrder: mode.item.sortOrder,
    values: Object.fromEntries(
      fields.map((field) => [
        field.externalId,
        formatDictionaryEntryInputValue(
          mode.item.values[field.externalId],
          field.dataType,
        ),
      ]),
    ) as Record<string, string>,
  };
}

function getFieldDescription(
  field: DictionaryField,
  t: ReturnType<typeof useTranslations>,
): string | undefined {
  const type = getDictionaryFieldTypeOption(field.dataType, field.format);

  if (type === "uuid_auto") {
    return t("fieldHints.uuid_auto");
  }

  if (type === "integer_identifier_auto") {
    return t("fieldHints.integer_identifier_auto");
  }

  if (type === "uuid") {
    return t("fieldHints.uuid");
  }

  if (type === "integer_identifier") {
    return t("fieldHints.integer_identifier");
  }

  return undefined;
}

function getInputMode(
  field: DictionaryField,
): "decimal" | "numeric" | undefined {
  const type = getDictionaryFieldTypeOption(field.dataType, field.format);

  if (
    type === "integer" ||
    type === "integer_identifier" ||
    type === "integer_identifier_auto"
  ) {
    return "numeric";
  }

  if (type === "number") {
    return "decimal";
  }

  return undefined;
}

function getInputType(field: DictionaryField): string {
  if (field.dataType === "date") {
    return "date";
  }

  if (field.dataType === "datetime") {
    return "datetime-local";
  }

  return "text";
}

function firstFilledValue(values: Record<string, string>): string {
  return Object.values(values).find((value) => value.trim()) ?? "";
}
