"""Stable identifiers and MVP limits for Agentic Context Resolver."""

DOCUMENT_AGENTIC_CONTEXT_RESOLVER_IMPLEMENTATION_ID = "document.extraction.agentic_context_resolver"
AGENTIC_MAX_GROUP_ATTRIBUTES = 24
AGENTIC_MAX_GROUP_REQUEST_BYTES = 32_000
AGENTIC_MAX_GROUP_ESTIMATED_OUTPUT_TOKENS = 12_000
AGENTIC_MAX_FINAL_CANDIDATES = 8
AGENTIC_MAX_FINAL_QUOTES = 16
AGENTIC_MAX_COMPLETION_TOKENS = 16_000
AGENTIC_MAX_CONCURRENCY = 4
AGENTIC_REQUEST_TIMEOUT_SECONDS = 120.0
AGENTIC_STEP_TIMEOUT_SECONDS = 600.0
AGENTIC_SECOND_PASS_PRESENT_CONFIDENCE_THRESHOLD = 0.0
AGENTIC_METADATA_CONFIDENCE = 1.0
AGENTIC_METADATA_NOT_CONFIRMED_CONFIDENCE = 0.5
